package com.leo.moviehunter.util;

public interface MHConstants {

    String BUNDLE_KEY_GENRE_ID = "BUNDLE_KEY_GENRE_ID";
    String BUNDLE_KEY_MOVIE_ID = "BUNDLE_KEY_MOVIE_ID";
    String BUNDLE_KEY_SEARCH_STRING = "BUNDLE_KEY_SEARCH_STRING";
    String BUNDLE_KEY_MOVIE_JSON = "BUNDLE_KEY_MOVIE_JSON";
    String BUNDLE_KEY_WATCH_ITEM_JSON = "BUNDLE_KEY_WATCH_ITEM_JSON";

    float MAX_MOVIE_SCORE = 100.0f;
}
